version: '3'
services:
  web:
    build:
      context: ./docker-jitsi-meet/web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CERTS}/web.crt:/config/certs/web.crt
      - ${CERTS}/web.key:/config/certs/web.key