version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CONFIG}/web:/config
      - ${CERTS}/web:/etc/ssl:ro
    restart: unless-stopped

  prosody:
    image: jitsi/prosody:stable-8044
    volumes:
      - ${CONFIG}/prosody:/config
    restart: unless-stopped

  jicofo:
    image: jitsi/jicofo:stable-8044
    volumes:
      - ${CONFIG}/jicofo:/config
    restart: unless-stopped

  jvb:
    image: jitsi/jvb:stable-8044
    ports:
      - "10000:10000/udp"
    volumes:
      - ${CONFIG}/jvb:/config
    restart: unless-stopped